import type { Metadata } from "next";
import "./globals.css";
import SessionContext from "@/context/SessionContext";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "fitTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <SessionContext>
          <SidebarProvider>{children}</SidebarProvider>
        </SessionContext>
      </body>
    </html>
  );
}
